import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  conatiner: {
    height: 170,
    position: 'relative',
    marginBottom: 16,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'black',
    opacity: 0.4,
  },
  image: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  details: {
    height: 90,
    width: '80%',
    borderWidth: 1,
    borderColor: '#fff',
    margin: 40,
    borderBottomColor: 'transparent',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  left: {
    height: 1,
    backgroundColor: 'white',
    width: '15%',
    position: 'absolute',
    bottom: -1,
    left: -1,
  },
  right: {
    height: 1,
    backgroundColor: 'white',
    width: '15%',
    position: 'absolute',
    bottom: -1,
    right: -1,
  },
  name: {
    fontSize: 16,
    color: 'white',
    textTransform: 'uppercase',
    fontWeight: '500',
    maxWidth: '75%',
    textAlign: 'center',
  },
  menu: {
    height: 200,
  },
  price: {
    color: 'white',
    fontSize: 20,
    marginBottom: -10,
    marginTop: 20,
  },
  hotels: {
    height: 220,
  },
  icon: {
    position: 'absolute',
    alignSelf: 'center',
  },
});
